// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksiyfkpbuibpijhysjuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzaXlma3BidWlicGlqaHlzanV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTU2NTksImV4cCI6MjA2ODM5MTY1OX0.5trUrbjdrlBIdX-EZEmMSCDtCO_STBm-LklHYe5obGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});