// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syvfpwkvqlaejgcyiyfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5dmZwd2t2cWxhZWpnY3lpeWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzE2NTUsImV4cCI6MjA2ODM0NzY1NX0.PlycZjWA0NefGim4gC_H_GLLyIn0v8awDez_5S_uBGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});